# Weboldal alapadatai
title: "Laktózmentes Blog"
description: "Az élet laktózmentes oldala"
url: "https://laktozmentes.github.io"
baseurl: "/site" # FONTOS: Most már pontosan megadjuk az alkönyvtárat!

# Gyűjtemények
collections:
  recipes:
    output: true
    permalink: /receptek/:path/

permalink: /blog/:title/

# Markdown és Szövegfeldolgozás
markdown: kramdown
highlighter: rouge
excerpt_separator: "" # Ezt írd vissza, különben a főoldalon a teljes cikk megjelenik!

# Webhely felépítése
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "recipes"
    values:
      layout: "recipe"

# Kizárások
exclude:
  - node_modules
  - tailwind.config.js
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - .github
  - README.md

# Pluginok
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap



